# Generated by Django 3.2 on 2021-07-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210705_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
