# Generated by Django 3.2 on 2021-07-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
