# Generated by Django 3.2 on 2021-07-08 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_auto_20210706_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('native_language', models.CharField(choices=[('English', 'ENGLISH'), ('French', 'FRENCH'), ('Spanish', 'SPANISH'), ('Portuguese', 'PORTUGUESE'), ('German', 'GERMAN'), ('Danish', 'DANISH'), ('Dutch', 'DUTCH'), ('Russian', 'RUSSIAN'), ('Italian', 'ITALIAN'), ('Greek', 'GREEK'), ('Polish', 'POLISH'), ('Hindi', 'HINDI'), ('Finnish', 'FINNISH'), ('Hungarian', 'HUNGARIAN'), ('Czech', 'CZECH'), ('Welsh', 'WELSH'), ('Swedish', 'SWEDISH')], max_length=50)),
                ('learning_language', models.CharField(choices=[('English', 'ENGLISH'), ('French', 'FRENCH'), ('Spanish', 'SPANISH'), ('Portuguese', 'PORTUGUESE'), ('German', 'GERMAN'), ('Danish', 'DANISH'), ('Dutch', 'DUTCH'), ('Russian', 'RUSSIAN'), ('Italian', 'ITALIAN'), ('Greek', 'GREEK'), ('Polish', 'POLISH'), ('Hindi', 'HINDI'), ('Finnish', 'FINNISH'), ('Hungarian', 'HUNGARIAN'), ('Czech', 'CZECH'), ('Welsh', 'WELSH'), ('Swedish', 'SWEDISH')], max_length=50)),
                ('students', models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
